[[Perl]]
arch = "aarch64"
git-tree-sha1 = "623a63e5730a5650454436750c1c4444fc8e9816"
os = "macos"

    [[Perl.download]]
    sha256 = "03a3169f036ea8b7b77d38997f411f289c429c9cb2a3b45de4dca434ce52f155"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.aarch64-apple-darwin.tar.gz"
[[Perl]]
arch = "aarch64"
git-tree-sha1 = "f18ef70a72b49b305f1ec72164f165ce841928a6"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "2cb72162b0f699467e11dd09e0e72d8437bf23d26a57134363e82f7fd93a1d9d"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.aarch64-linux-gnu.tar.gz"
[[Perl]]
arch = "aarch64"
git-tree-sha1 = "99ac45ce6f9b78643ec829b57af28f838c4a4b0e"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "92b78c088982483177cbd5e5bc5039fea3cf56da308742ac828b2af6bfa817cb"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.aarch64-linux-musl.tar.gz"
[[Perl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "45067c6785e1eddc2801201a18381c8cb9bffc91"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "79103b398c8ed70e56df077d035ce09bfd677d4b1040a9b26df4d020b0a8c8c7"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.armv7l-linux-gnueabihf.tar.gz"
[[Perl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f66ff973723b5d90ee9baaf789c2cc6d75ca60e9"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "572ca2095de6a958b892b319e4df4c3a196d5062e5b14b15aa1ee346c01ff5bd"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.armv7l-linux-musleabihf.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "44c7cb928e7ecd9c2c571aa61d9468ce7ee98694"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "40fc5d16b54c5bc48508a8c77d4d5f8fec3caf46d8df0f398188f6102e5091a3"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.i686-linux-gnu.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "5c08af3dd676a7771e6a605133b7bf902512c30d"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "8ca605abe905e7628aba344a288514c5471160a66390e3fc1a25e832481c3e8c"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.i686-linux-musl.tar.gz"
[[Perl]]
arch = "powerpc64le"
git-tree-sha1 = "92f3fb80cd5568bb190840de0b655da05ef14300"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "fb81d85f6d2c75fffe6caf41983d030483f8abb1495009868c34e27f0d378d93"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.powerpc64le-linux-gnu.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "22325e37a6010e33da82bf90b5f51b7cb6ddc687"
os = "macos"

    [[Perl.download]]
    sha256 = "375a3a5bfa0353ee3d7688f62f7e169866bbcec554cd626dfff6b81795ea484d"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.x86_64-apple-darwin.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "07ef9c18296d78f06f5b946ed2c127b4aae6ac2c"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "11cffe81b5eef597ae4d5703200151228d1173c402dbf4d83e487e2b4d055f25"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.x86_64-linux-gnu.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "0562092f091d541ff10673bb05e615cacbcff9ee"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "056ea6b89d8f81ad7b21fb93d7f05d07d64b8632fe822122da12cb55dffa18aa"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.x86_64-linux-musl.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "2dd2adf85fc590df1091d5962cca1951b4ed1983"
os = "freebsd"

    [[Perl.download]]
    sha256 = "b3e4022b6fee5e89e2bf6ef3d107b5971ef027a8dbb134a48c10f5c757fb171d"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.0+2/Perl.v5.34.0.x86_64-unknown-freebsd.tar.gz"
