[[Perl]]
arch = "aarch64"
git-tree-sha1 = "ab061322ff58d69ac4ac11940d47c0983557c2fc"
os = "macos"

    [[Perl.download]]
    sha256 = "1c78c3b03ce77aa2890180d4334cee958ee836a57b0178b163196299a05e504a"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.aarch64-apple-darwin.tar.gz"
[[Perl]]
arch = "aarch64"
git-tree-sha1 = "cfd6c4064ac1bc0fc9f6a669def15f7080169f71"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "6cd2763ec04aa47f933a4d23b084c5f0dcfc77ac8adcec790a25f639fb266af0"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.aarch64-linux-gnu.tar.gz"
[[Perl]]
arch = "aarch64"
git-tree-sha1 = "3040629400249ff0a3ba10ed92f7573b9b0dbf7e"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "e45f74e9fb1361ac86c33003ba27141a6d10a49df5c0e8fbe7932551ea43664b"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.aarch64-linux-musl.tar.gz"
[[Perl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43bb32163cd51c4de77e5a6d27c72c03dcc08701"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "baaa49650869d5ac2e37bc5ed3e7d9efa328a556e617490daa5bbf3ffe6b072c"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.armv7l-linux-gnueabihf.tar.gz"
[[Perl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e89c6367fbd9e5f4662411edf457b1e61ad28d8"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "1d2c9f64fe3b75d393fb774c40fe65fe5f22213bef7562d302d2e8e7c97e5291"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.armv7l-linux-musleabihf.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "8dac6f74f449eb200b24a0b841b4a995cef5a9db"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "23ca5b8a3221cb887fae0a7061c837b5d0ede213ff8773dda66fd9a25d09db7f"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.i686-linux-gnu.tar.gz"
[[Perl]]
arch = "i686"
git-tree-sha1 = "3166294802380887faef3b86807c0f4b00e0f693"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "6a660fc3bd31563a795901c78b5490d55835b102961307fe2efb7c62719d43a0"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.i686-linux-musl.tar.gz"
[[Perl]]
arch = "powerpc64le"
git-tree-sha1 = "ce3c0c6415d96f07374fd2efa4d23dce60c713a0"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "6df5b3d91e12e031e6b486afa3ebe2795bca95bc7875cc58ff9cfeed282786f1"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.powerpc64le-linux-gnu.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "941ff2468bc632e5c9be538b71ff79995fb80c7b"
os = "macos"

    [[Perl.download]]
    sha256 = "c1c8b6eafe78456a24fad84dea48046f55d55de71ef663d385585ff338c63d42"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.x86_64-apple-darwin.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "3696ccdfa324bc69f48c9dc400f39f1305a4b320"
libc = "glibc"
os = "linux"

    [[Perl.download]]
    sha256 = "20bc695c7e61ec7e7d7171ea8d7fddfe3ad802277726b8412cb0b8c604035dc7"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.x86_64-linux-gnu.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "d97f4e9e4b769c7e4c497e7dd7209055371be660"
libc = "musl"
os = "linux"

    [[Perl.download]]
    sha256 = "59b0fd7a3dd9044417e0238ac072abf4ea38f26626b5eb886c64d3e3d9568b41"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.x86_64-linux-musl.tar.gz"
[[Perl]]
arch = "x86_64"
git-tree-sha1 = "76e680e692f10c718a7930dfcea7ad4f43f4df93"
os = "freebsd"

    [[Perl.download]]
    sha256 = "8ff5191da8431296839064b647085629303ccc70d35a0dbaf92451a52aacecb6"
    url = "https://github.com/JuliaBinaryWrappers/Perl_jll.jl/releases/download/Perl-v5.34.1+0/Perl.v5.34.1.x86_64-unknown-freebsd.tar.gz"
